version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
networks:
  broker-kafka:
    driver: bridge
