version: '3.8'

services:
  postgres:
    image: postgres:17.3
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  metamodel:
    image: ghcr.io/fintlabs/fint-core-consumer-metamodel:latest
    networks:
      - network-bridge
    ports:
      - 8081:8080
networks:
  network-bridge:
    driver: bridge
