fint:
  metamodel: http://fint-core-consumer-metamodel:8080
spring:
  datasource:
    url: ${fint.database.url}
    username: ${fint.database.username}
    password: ${fint.database.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update