fint:
  endpoints:
    metamodel: http://localhost:8081
    admin: http://localhost:8082
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres