fint:
  endpoints:
    metamodel: http://fint-core-consumer-metamodel:8080
spring:
  r2dbc:
    url: ${fint.database.url}
    username: ${fint.database.username}
    password: ${fint.database.password}
